task_queue:
	gcc -o task_queue task_queue.c -O3 -fopenmp -lm

task_queue_without_alpha_beta:
	gcc -o task_queue_without_alpha_beta task_queue_without_alpha_beta.c -O3 -fopenmp -lm

clean:
	rm -r task_queue task_queue_without_alpha_beta